name: rl_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch-cpu
  - torchvision-cpu
  - numpy
  - pillow
  - pyyaml
  - pip
  - pip:
      - stable-baselines3
      - gymnasium
      - ale-py
      - ray
      - torchrl
      - tensorboard
      - matplotlib
      - pandas
      - opencv-python
      - moviepy
      - pytest
      - mypy
      -  # add other pip packages you actually need
